### ISSUE TITLE
SPICE?

### ISSUE THREAD

**Issue by mailinglists35** [stweil/qemu#8]
Thank you for your work, Stefan!

Can SPICE be integrated?

I read but could not find anything about it on https://wiki.qemu.org/Hosts/W32 and https://qemu.weilnetz.de/FAQ

Is it technically difficult/impossible to integrate it, or are there software licensing issues preventing it to get binary distributed into qemu for windows?

My use case would be to have the `-vga qxl` option and for smoother mouse movement in the guest (do I really need qxl for smoother windows guest mouse?)

Thanks

**Comment by mailinglists35** [comment]
update: `-display sdl` makes vast mouse smoothness improvement, but there is an annoying small lag.

**Comment by stweil** [comment]
Did you try one of the recent versions? They should support SPICE, although I did not test that myself.

**Comment by mailinglists35** [comment]
I am running the latest from `qemu.weilnetz.de`

````
C:\Program Files\qemu>qemu-system-x86_64.exe --version
QEMU emulator version 7.1.90 (v7.2.0-rc0-11935-gffa732b268-dirty)
````

qemu.weilnetz.de seems down at the moment: https://downforeveryoneorjustme.com/qemu.weilnetz.de

**Comment by stweil** [comment]
Thanks for reporting. That was caused by an incomplete update. It works now again.

**Comment by mailinglists35** [comment]
oops, looks like I was running the wrong version, I was doing simultaneously local and over remote desktop, the one I tested was in fact an older qemu without spice. I confirm the latest indeed does have `-vga qxl`, `-display spice-app` and all other spice related command line arguments!
